signingConfigs: [
  {
    "name": "default",
    "type": "HarmonyOS",
    "material": {
      "storeFile": "D:/template/signature/attraction/scenic.p12",
      "storePassword": "000000194807F6806969FC1B923C7105C097B26EBA23D8C29D0CBD458D175191A20F93D2FEFBBEC2B3",
      "keyAlias": "scenicHarmonyOS",
      "keyPassword": "000000193BBE35FF9A4DB6A326171CD2BC39A86B14E61D61130D0E8C561D83245B651AB0E682C2021D",
      "signAlg": "SHA256withECDSA",
      "profile": "D:/template/signature/attraction/scenicDebug.p7b",
      "certpath": "D:/template/signature/attraction/scenic.cer"
    }
  }
]
bundleName: com.atomicservice.6917560304091745774
