signingConfigs: [
      {
        "name": "default",
        "type": "HarmonyOS",
        "material": {
          "certpath": "C:\\Users\\HW\\.ohos\\config\\default_TouristAttraction1.0.3_YWEFj6kXN9kzY0EfLPhgnAlwOTMJcKUKs-yJD1fN01c=.cer",
          "keyAlias": "debugKey",
          "keyPassword": "0000001B7E3812DB48CDE15066345E64901EB4251232806322698EAAFCCC8FD231D9E4100DF6309F316C83",
          "profile": "C:\\Users\\HW\\.ohos\\config\\default_TouristAttraction1.0.3_YWEFj6kXN9kzY0EfLPhgnAlwOTMJcKUKs-yJD1fN01c=.p7b",
          "signAlg": "SHA256withECDSA",
          "storeFile": "C:\\Users\\HW\\.ohos\\config\\default_TouristAttraction1.0.3_YWEFj6kXN9kzY0EfLPhgnAlwOTMJcKUKs-yJD1fN01c=.p12",
          "storePassword": "0000001BB259765402FFF0E81E967C76701E12D829FFE5B505EE179FD91223D763DA70F1F0E921BC22BA5D"
        }
      }
    ]
bundleName: com.atomicservice.6917578576540763236